use std::env;
use std::time::Duration;

use git2::Repository;
use indicatif::{ProgressBar, ProgressStyle};

use crate::cli::Platform;
use crate::context::Context;
use crate::error::ShipItError;
use crate::common::{lookup_github_identifier, lookup_gitlab_project_id, open_github_pr, open_gitlab_mr, summarize_with_ollama};

pub async fn branch_to_branch(
    ctx: &Context,
    args_source: String,
    args_target: String,
    args_dir: Option<String>,
    args_id: Option<String>,
    args_platform: Option<Platform>,
    args_remote: String,
    args_prompt: Option<String>,
) -> Result<(), ShipItError> {
    let dir = match args_dir {
        Some(path) => std::path::PathBuf::from(path),
        None => match env::current_dir() {
            Ok(path) => path,
            Err(e) => panic!("Failed to get the source directory: {}", e),
        },
    };
    let repo = match Repository::init(dir) {
        Ok(repo) => repo,
        Err(e) => panic!("Failed to find a git repo at: {}", e),
    };
    println!(
        "Found a git repository at {}",
        repo.path().to_str().unwrap_or("NOT FOUND")
    );

    // get branch and most recent commit structs for the target and source branches
    let source = repo.find_branch(&args_source, git2::BranchType::Local).map_err(|e| ShipItError::Git(e))?;
    let target = repo.find_branch(&args_target, git2::BranchType::Local).map_err(|e| ShipItError::Git(e))?;
    let target_oid = target
        .get()
        .target()
        .ok_or_else(|| ShipItError::Git(git2::Error::from_str("Failed to find a valid commit for the target branch!")))?;

    // find the most recent target commit on the source branch
    // this will help determine which commits are not present on the target branch
    let target_oid_on_source = repo.find_commit(target_oid).unwrap();

    // create a vector of the commit ids that are on the source, but not the
    // target branch.  display the messages for those commit ids
    // and create a revision walk for the source branch
    let mut revwalk = repo.revwalk().map_err(|e| ShipItError::Git(e))?;
    let root_ref = "refs/heads/";
    let branch_ref = source
        .name().map_err(|e| ShipItError::Git(e))?
        .ok_or_else(|| ShipItError::Git(git2::Error::from_str("Failed to unwrap the name of the source branch!")))?;
    let full_ref = root_ref.to_string() + branch_ref;
    revwalk.push_ref(&full_ref).map_err(|e| ShipItError::Git(e))?;
    let target_oid_hash = target_oid_on_source.id();

    // hide commits that are on both branches
    // essentially tells the walker to stop here
    revwalk.hide(target_oid_hash).map_err(|e| ShipItError::Git(e))?;
    let mut commits = Vec::new();
    for oid in revwalk {
        commits.push(oid.map_err(|e| ShipItError::Git(e))?);
    }

    // display the messages of the discovered commits
    let mut messages = Vec::new();
    for commit in commits {
        let release_oid = repo.find_commit(commit).unwrap();
        let msg = release_oid
            .message()
            .ok_or_else(|| ShipItError::Git(git2::Error::from_str("Failed to unwrap the message of a release commit!")))?
            .to_string();
        messages.push(format!("{} {}", msg, release_oid.id().to_string()));
    }
    let description = messages.join(",");

    if description.is_empty() {
        println!("No commits found between '{}' and '{}'. Nothing to do.", args_source, args_target);
        return Ok(());
    }

    // ask a local llm to summarize these commit messages
    let mut summary = if ctx.settings.shipit.ai {
        let mut ollama = ctx.settings.ollama.clone();
        if let Some(prompt) = args_prompt {
            ollama.prompt = prompt;
        }
        let spinner = ProgressBar::new_spinner();
        spinner.set_style(
            ProgressStyle::default_spinner()
                .tick_strings(&["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧", "⠇", "⠏"])
                .template("{spinner:.cyan} {msg}")
                .unwrap(),
        );
        spinner.set_message(format!("Asking Ollama to categorize the commits({})...", ollama.model));
        spinner.enable_steady_tick(Duration::from_millis(80));

        let result = summarize_with_ollama(
            &description, &ollama
        ).await.or_else(|_e| Err(ShipItError::Error("Failed to summarize with Ollama!".to_string())));

        spinner.finish_and_clear();

        let result = result?;
        println!("The merge request description is:\n\n{}", result);
        result
    } else {
        description
    };
    summary += "\n\n\n*This request was generated by [Shipit](https://gitshipit.net)* 🚢";

    if ctx.settings.shipit.dryrun {
        println!("\n\nDry run complete! Re-run without the dry-run flag to open a request.");
        return Ok(());
    }

    // always fetch the remote URL — needed both for platform detection and ID auto-lookup
    let remote_url = {
        let remote = repo.find_remote(&args_remote).map_err(|e| ShipItError::Git(e))?;
        remote.url()
            .ok_or_else(|| ShipItError::Error(format!("The '{}' remote has no URL.", args_remote)))?
            .to_string()
    };

    // determine the platform to use:
    // use --platform flag if provided, otherwise detect from origin remote url
    let (is_github, is_gitlab) = match args_platform {
        Some(Platform::Github) => (true, false),
        Some(Platform::Gitlab) => (false, true),
        None => (remote_url.contains("github"), remote_url.contains("gitlab")),
    };

    // resolve the project identifier:
    // use --id if provided, otherwise look it up from the remote url via the platform api
    let resolved_id: String = match args_id {
        Some(id) => id,
        None => {
            if is_github {
                lookup_github_identifier(&remote_url)
                    .map_err(|e| ShipItError::Error(format!("Failed to detect GitHub owner/repo from remote URL: {}", e)))?
            } else if is_gitlab {
                let token = ctx.settings.gitlab.token.as_deref()
                    .ok_or_else(|| ShipItError::Error("GitLab token is required to look up the project ID.".to_string()))?;
                let id = lookup_gitlab_project_id(&remote_url, &ctx.settings.gitlab.domain, token).await
                    .map_err(|e| ShipItError::Error(format!("Failed to look up GitLab project ID from remote URL: {}", e)))?;
                println!("Auto-detected GitLab project ID: {}", id);
                id.to_string()
            } else {
                return Err(ShipItError::Error("Could not determine platform. Use '--platform github' or '--platform gitlab' to specify it explicitly.".to_string()));
            }
        }
    };

    // check if the local source branch is ahead of its remote tracking branch
    let needs_push = {
        let local_oid = source.get().target()
            .ok_or_else(|| ShipItError::Git(git2::Error::from_str("Failed to get source branch OID")))?;
        let remote_tracking_ref = format!("refs/remotes/{}/{}", args_remote, args_source);
        match repo.find_reference(&remote_tracking_ref) {
            Ok(remote_ref) => match remote_ref.target() {
                Some(remote_oid) => {
                    let (ahead, _) = repo.graph_ahead_behind(local_oid, remote_oid)
                        .map_err(|e| ShipItError::Git(e))?;
                    ahead > 0
                }
                None => true,
            },
            Err(_) => true, // no remote tracking branch yet
        }
    };

    if needs_push {
        println!(
            "\n\nYour local source branch is ahead of the remote. Please push it, then press Enter to continue:\n\n  git push {} {}\n",
            args_remote, args_source
        );
        let mut input = String::new();
        std::io::stdin().read_line(&mut input).map_err(|e| ShipItError::Error(format!("Failed to read input: {}", e)))?;
    }

    if is_github {
        let parts: Vec<&str> = resolved_id.splitn(2, '/').collect();
        if parts.len() != 2 {
            return Err(ShipItError::Error(format!("GitHub project identifier '{}' must be in 'owner/repo' format.", resolved_id)));
        }
        let token = ctx.settings.github.token.as_deref().unwrap();
        let (owner, gh_repo) = (parts[0], parts[1]);
        let pr_url = open_github_pr(
            &args_source, &args_target, &ctx.settings.github.domain,
            token, owner, gh_repo, &summary,
        ).await.map_err(|e| ShipItError::Error(format!("Failed to open a GitHub PR: {}", e)))?;
        println!("\n\nThe pull request is available at:\n\n{}", pr_url);
    } else if is_gitlab {
        let project_id: u64 = resolved_id.parse()
            .map_err(|_| ShipItError::Error(format!("GitLab project identifier '{}' must be a numeric project ID.", resolved_id)))?;
        let token = ctx.settings.gitlab.token.as_deref().unwrap();
        let mr_url = open_gitlab_mr(
            &args_source, &args_target, &ctx.settings.gitlab.domain,
            token, &project_id, &summary,
        ).await.map_err(|e| ShipItError::Error(format!("Failed to open a GitLab MR: {}", e)))?;
        println!("\n\nThe merge request is available at:\n\n{}", mr_url["web_url"]);
    } else {
        return Err(ShipItError::Error("Could not determine platform. Use '--platform github' or '--platform gitlab' to specify it explicitly.".to_string()));
    }

    Ok(())
}
