use crate::cli::B2bArgs;
use crate::context::Context;
use crate::error::ShipItError;
use crate::common::{
    categorize_commits, check_needs_push, collect_commits, collect_messages, enrich_messages,
    open_platform_mr, open_repo, resolve_project_id, resolve_remote_url, suggest_title,
    OllamaAgent, ShipitAgent,
};
use crate::common::agent::Agent;

pub async fn branch_to_branch(ctx: &Context, args: B2bArgs) -> Result<(), ShipItError> {
    let repo = open_repo(args.dir);
    let source = repo.find_branch(&args.source, git2::BranchType::Local).map_err(|e| ShipItError::Git(e))?;

    // Skip commit collection only when both description and title are explicitly provided,
    // since messages may still be needed for title suggestion even with a custom description.
    let messages = if args.description.is_some() && args.title.is_some() {
        vec![]
    } else {
        let commits = collect_commits(&repo, &source, &args.target, args.only_merges)?;
        let msgs = collect_messages(&repo, commits)?;
        enrich_messages(ctx, &repo, &args.remote, msgs).await
    };

    let refs: Vec<&str> = messages.iter().map(|s| s.as_str()).collect();
    let categorized = categorize_commits(&refs);

    let mut summary = if let Some(provided) = args.description {
        provided
    } else {
        let description = messages.join(",");

        if description.is_empty() {
            tracing::warn!("No commits found between '{}' and '{}'. Nothing to do.", args.source, args.target);
            return Ok(());
        }

        match ctx.settings.shipit.agent.as_str() {
            "shipit" => ShipitAgent.generate_summary(&description, &categorized).await?,
            "ollama" => {
                let mut ollama = ctx.settings.ollama.clone();
                if let Some(p) = args.prompt { ollama.prompt = p; }
                OllamaAgent::new(ollama).generate_summary(&description, &categorized).await?
            }
            "" => description,
            unknown => return Err(ShipItError::Error(format!("Unknown ai agent: '{}'", unknown))),
        }
    };

    crate::output::print_content("The merge request description is:", &summary);
    if !args.no_sign {
        summary += "\n\n\n*This request was generated by [Shipit](https://gitshipit.net)* 🚢";
    }

    let remote_url = resolve_remote_url(&repo, &args.remote)?;
    let (is_github, is_gitlab) = (remote_url.contains("github"), remote_url.contains("gitlab"));
    let resolved_id = resolve_project_id(ctx, &remote_url, args.id, is_github, is_gitlab).await?;

    let title = if let Some(t) = args.title {
        t
    } else {
        suggest_title(ctx, is_github, is_gitlab, &resolved_id, &categorized).await
            .unwrap_or_else(|| format!("{} to {}", args.source, args.target))
    };

    crate::output::print_content("The merge request title is:", &title);

    if ctx.settings.shipit.dryrun {
        crate::output::print_dryrun("open a request");
        return Ok(());
    }

    if check_needs_push(&repo, &source, &args.remote, &args.source)? {
        crate::output::print_push_prompt(&args.remote, &args.source);
        let mut input = String::new();
        std::io::stdin().read_line(&mut input).map_err(|e| ShipItError::Error(format!("Failed to read input: {}", e)))?;
    }

    let url = open_platform_mr(ctx, &resolved_id, &args.source, &args.target, &title, &summary, is_github, is_gitlab).await?;
    crate::output::print_url(&url);

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::cli::B2bArgs;
    use crate::context::Context;
    use crate::settings::{
        GithubSettings, GitlabSettings, OllamaSettings, Settings, ShipitSettings,
    };
    use git2::{Repository, Signature};
    use tempfile::TempDir;

    fn make_ctx(
        dryrun: bool,
        agent: &str,
        gitlab_token: Option<&str>,
        github_token: Option<&str>,
    ) -> Context {
        Context {
            settings: Settings {
                shipit: ShipitSettings {
                    agent: agent.to_string(),
                    commits: "custom".to_string(),
                    dryrun,
                },
                ollama: OllamaSettings::default(),
                gitlab: GitlabSettings {
                    domain: "gitlab.com".to_string(),
                    token: gitlab_token.map(|t| t.to_string()),
                },
                github: GithubSettings {
                    domain: "github.com".to_string(),
                    token: github_token.map(|t| t.to_string()),
                },
            },
        }
    }

    /// Initialises a bare repo with a single base commit on HEAD and two named
    /// branches: `target_name` at the base commit and `source_name` with one
    /// extra commit on top.  Returns (TempDir, Repository, base_oid, source_oid).
    fn setup_diverged_repo(
        source_name: &str,
        target_name: &str,
    ) -> (TempDir, Repository, git2::Oid, git2::Oid) {
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("Test User", "test@example.com").unwrap();

        let tree_id = repo.index().unwrap().write_tree().unwrap();

        let (base_oid, source_oid) = {
            let tree = repo.find_tree(tree_id).unwrap();

            let base_oid = repo
                .commit(Some("HEAD"), &sig, &sig, "base commit", &tree, &[])
                .unwrap();
            let base_commit = repo.find_commit(base_oid).unwrap();

            repo.branch(target_name, &base_commit, false).unwrap();
            repo.branch(source_name, &base_commit, false).unwrap();

            let source_ref = format!("refs/heads/{}", source_name);
            let source_oid = repo
                .commit(
                    Some(&source_ref),
                    &sig,
                    &sig,
                    "feat: add something",
                    &tree,
                    &[&base_commit],
                )
                .unwrap();

            (base_oid, source_oid)
        };

        (dir, repo, base_oid, source_oid)
    }

    /// Creates a remote tracking ref so that `needs_push` evaluates to `false`
    /// (local and remote are at the same commit).
    fn pin_remote_tracking(repo: &Repository, remote: &str, branch: &str, oid: git2::Oid) {
        let ref_name = format!("refs/remotes/{}/{}", remote, branch);
        repo.reference(&ref_name, oid, false, "test").unwrap();
    }

    #[tokio::test]
    async fn test_missing_source_branch_returns_git_error() {
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("t", "t@t.com").unwrap();
        let tree_id = repo.index().unwrap().write_tree().unwrap();
        let tree = repo.find_tree(tree_id).unwrap();
        repo.commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
            .unwrap();

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "does-not-exist".to_string(),
                target: "main".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Git(_))));
    }

    #[tokio::test]
    async fn test_missing_target_branch_without_description_returns_git_error() {
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("t", "t@t.com").unwrap();
        let tree_id = repo.index().unwrap().write_tree().unwrap();
        let tree = repo.find_tree(tree_id).unwrap();
        let base_oid = repo
            .commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
            .unwrap();
        let base_commit = repo.find_commit(base_oid).unwrap();
        repo.branch("source", &base_commit, false).unwrap();

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "does-not-exist".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                // no description - code must look up the target branch
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Git(_))));
    }

    #[tokio::test]
    async fn test_both_title_and_description_skips_target_branch_lookup() {
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("t", "t@t.com").unwrap();
        let tree_id = repo.index().unwrap().write_tree().unwrap();
        let tree = repo.find_tree(tree_id).unwrap();
        let base_oid = repo
            .commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
            .unwrap();
        let base_commit = repo.find_commit(base_oid).unwrap();
        repo.branch("source", &base_commit, false).unwrap();
        repo.remote("origin", "https://github.com/owner/repo.git").unwrap();

        // Both title and description are provided — commit collection is skipped entirely,
        // so a nonexistent target branch does not cause an error.
        let ctx = make_ctx(true, "", None, None); // dryrun - exits after title generation
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "nonexistent-target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                title: Some("My custom title".to_string()),
                description: Some("My custom description".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_no_commits_between_branches_returns_ok_early() {
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("t", "t@t.com").unwrap();
        let tree_id = repo.index().unwrap().write_tree().unwrap();
        let tree = repo.find_tree(tree_id).unwrap();
        let base_oid = repo
            .commit(Some("HEAD"), &sig, &sig, "init", &tree, &[])
            .unwrap();
        let base_commit = repo.find_commit(base_oid).unwrap();
        repo.branch("source", &base_commit, false).unwrap();
        repo.branch("target", &base_commit, false).unwrap();

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_dryrun_exits_after_commit_discovery_without_reaching_remote() {
        let (dir, repo, _, _) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://github.com/owner/repo.git").unwrap();

        let ctx = make_ctx(true, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_dryrun_with_description_exits_without_reaching_remote() {
        let (dir, repo, _, _) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://github.com/owner/repo.git").unwrap();

        let ctx = make_ctx(true, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                description: Some("Provided description".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_shipit_agent_categorizes_commits_and_returns_ok() {
        let (dir, repo, _, _) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://github.com/owner/repo.git").unwrap();

        let ctx = make_ctx(true, "shipit", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_unknown_agent_name_returns_shipit_error() {
        let (dir, _repo, _, _) = setup_diverged_repo("source", "target");

        let ctx = make_ctx(false, "unknown_agent", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Error(msg)) if msg.contains("unknown_agent")));
    }

    #[tokio::test]
    async fn test_missing_remote_returns_git_error() {
        let (dir, _repo, _, _) = setup_diverged_repo("source", "target");

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                description: Some("desc".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Git(_))));
    }

    #[tokio::test]
    async fn test_url_without_github_or_gitlab_returns_error() {
        let (dir, repo, _, _) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://bitbucket.org/owner/repo.git")
            .unwrap();

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                description: Some("desc".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Error(_))));
    }

    #[tokio::test]
    async fn test_auto_detect_gitlab_url_without_token_returns_error() {
        let (dir, repo, _, _) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://gitlab.com/owner/repo.git")
            .unwrap();

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                description: Some("desc".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Error(_))));
    }

    #[tokio::test]
    async fn test_github_id_without_slash_returns_format_error() {
        let (dir, repo, _, source_oid) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://github.com/owner/repo.git")
            .unwrap();
        pin_remote_tracking(&repo, "origin", "source", source_oid);

        let ctx = make_ctx(false, "", None, Some("fake-token"));
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                id: Some("noslash".to_string()),
                remote: "origin".to_string(),
                description: Some("desc".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Error(msg)) if msg.contains("owner/repo")));
    }

    #[tokio::test]
    async fn test_gitlab_non_numeric_project_id_returns_error() {
        let (dir, repo, _, source_oid) = setup_diverged_repo("source", "target");
        repo.remote("origin", "https://gitlab.com/owner/repo.git")
            .unwrap();
        pin_remote_tracking(&repo, "origin", "source", source_oid);

        let ctx = make_ctx(false, "", Some("fake-token"), None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                id: Some("not-a-number".to_string()),
                remote: "origin".to_string(),
                description: Some("desc".to_string()),
                ..Default::default()
            },
        )
        .await;

        assert!(matches!(result, Err(ShipItError::Error(msg)) if msg.contains("numeric")));
    }

    #[tokio::test]
    async fn test_only_merges_filters_out_regular_commits() {
        // The diverged repo has one regular (non-merge) commit on the source branch.
        // With only_merges=true that commit is filtered out, so the description is
        // empty and the function returns Ok early.
        let (dir, _repo, _, _) = setup_diverged_repo("source", "target");

        let ctx = make_ctx(false, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                only_merges: true,
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }

    #[tokio::test]
    async fn test_only_merges_includes_merge_commits() {
        // Build a repo where the source branch has a real merge commit (two parents).
        let dir = TempDir::new().unwrap();
        let repo = Repository::init(dir.path()).unwrap();
        let sig = Signature::now("Test User", "test@example.com").unwrap();
        let tree_id = repo.index().unwrap().write_tree().unwrap();
        let tree = repo.find_tree(tree_id).unwrap();

        // base commit - shared ancestor
        let base_oid = repo
            .commit(Some("HEAD"), &sig, &sig, "base commit", &tree, &[])
            .unwrap();
        let base_commit = repo.find_commit(base_oid).unwrap();

        // target branch sits at the base
        repo.branch("target", &base_commit, false).unwrap();

        // feature commit branching off base
        let feature_oid = repo
            .commit(None, &sig, &sig, "feat: feature", &tree, &[&base_commit])
            .unwrap();
        let feature_commit = repo.find_commit(feature_oid).unwrap();

        // merge commit on source that joins base + feature (two parents)
        let source_ref = "refs/heads/source";
        repo.commit(
            Some(source_ref),
            &sig,
            &sig,
            "Merge branch 'feature' into source",
            &tree,
            &[&base_commit, &feature_commit],
        )
        .unwrap();

        repo.remote("origin", "https://github.com/owner/repo.git").unwrap();

        let ctx = make_ctx(true, "", None, None);
        let result = branch_to_branch(
            &ctx,
            B2bArgs {
                source: "source".to_string(),
                target: "target".to_string(),
                dir: Some(dir.path().to_str().unwrap().to_string()),
                remote: "origin".to_string(),
                only_merges: true,
                ..Default::default()
            },
        )
        .await;

        assert!(result.is_ok());
    }
}
