use clap::builder::styling::{AnsiColor, Effects, Styles};
use clap::{Args, Parser, Subcommand, ValueEnum};

fn styles() -> Styles {
    Styles::styled()
        .header(AnsiColor::Green.on_default() | Effects::BOLD)
        .usage(AnsiColor::Green.on_default() | Effects::BOLD)
        .literal(AnsiColor::Cyan.on_default() | Effects::BOLD)
        .placeholder(AnsiColor::Cyan.on_default())
        .error(AnsiColor::Red.on_default() | Effects::BOLD)
        .valid(AnsiColor::Cyan.on_default() | Effects::BOLD)
        .invalid(AnsiColor::Yellow.on_default() | Effects::BOLD)
}

#[derive(Debug, Clone, ValueEnum)]
pub enum Agent {
    Ollama,
    Shipit,
}

#[derive(Args, Debug, Default)]
pub struct B2bArgs {
    #[arg(help = "Source branch to open the merge/pull request from")]
    pub source: String,
    #[arg(help = "Target branch to merge into")]
    pub target: String,
    #[arg(
        long,
        value_enum,
        help = "Use an agent to generate the merge/pull request title and description (e.g., ollama, shipit)"
    )]
    pub agent: Option<Agent>,
    #[arg(
        long,
        help = "Print the merge/pull request details without creating it"
    )]
    pub dry_run: bool,
    #[arg(
        long,
        help = "Path to the git repository (defaults to current directory)"
    )]
    pub dir: Option<String>,
    #[arg(
        long,
        help = "GitLab project id or GitHub 'owner/repo' (auto-detected from remote url if not provided)"
    )]
    pub id: Option<String>,
    #[arg(long, default_value = "origin", help = "Name of the git remote to use")]
    pub remote: String,
    #[arg(
        long,
        help = "Prompt prefix to send to Ollama (overrides the config file value)"
    )]
    pub prompt: Option<String>,
    #[arg(
        long,
        help = "Title to use for the merge/pull request (defaults to 'source to target')"
    )]
    pub title: Option<String>,
    #[arg(
        long,
        help = "Description to use for the merge/pull request (skips commit discovery and ai summary)"
    )]
    pub description: Option<String>,
    #[arg(long, help = "Only include merge commits in the discovered commits")]
    pub only_merges: bool,
    #[arg(long, help = "Do not append the 'generated by Shipit' line to the description")]
    pub no_sign: bool,
}

#[derive(Args, Debug, Default)]
pub struct B2tArgs {
    #[arg(help = "Branch to create the tag on")]
    pub branch: String,
    #[arg(help = "Name of the tag to create")]
    pub tag: String,
    #[arg(
        long,
        value_enum,
        help = "Use an agent to generate the tag notes (e.g., ollama, shipit)"
    )]
    pub agent: Option<Agent>,
    #[arg(long, help = "Print the tag notes without creating it")]
    pub dry_run: bool,
    #[arg(
        long,
        help = "Path to the git repository (defaults to current directory)"
    )]
    pub dir: Option<String>,
    #[arg(
        long,
        help = "GitLab project id or GitHub 'owner/repo' (auto-detected from remote url if not provided)"
    )]
    pub id: Option<String>,
    #[arg(long, default_value = "origin", help = "Name of the git remote to use")]
    pub remote: String,
    #[arg(
        long,
        help = "Prompt prefix to send to Ollama (overrides the config file value)"
    )]
    pub prompt: Option<String>,
    #[arg(
        long,
        help = "Description to use for the tag notes (skips commit discovery and ai summary)"
    )]
    pub description: Option<String>,
    #[arg(long, help = "Only include merge commits in the discovered commits")]
    pub only_merges: bool,
    #[arg(
        long,
        help = "The most recent tag to compare against (defaults to auto-detected most recent tag on the branch)"
    )]
    pub latest_tag: Option<String>,
    #[arg(long, help = "Do not append the 'generated by Shipit' line to the tag notes")]
    pub no_sign: bool,
}

#[derive(Parser)]
#[command(styles = styles())]
#[command(subcommand_required = false)]
#[command(arg_required_else_help = true)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Option<Commands>,
    #[arg(
        short = 'v',
        long,
        action = clap::ArgAction::Count,
        global = true,
        help = "Increase log verbosity (-v for info, -vv for debug)"
    )]
    pub verbose: u8,
    #[arg(long, hide = true)]
    pub markdown_help: bool,
}

#[derive(Args, Debug, Default)]
pub struct T2rArgs {
    #[arg(
        long,
        help = "Tag to create the release for (defaults to the latest tag on the platform)"
    )]
    pub tag: Option<String>,
    #[arg(long, help = "Print the release details without creating it")]
    pub dry_run: bool,
    #[arg(
        long,
        help = "Path to the git repository (defaults to current directory)"
    )]
    pub dir: Option<String>,
    #[arg(
        long,
        help = "GitLab project id or GitHub 'owner/repo' (auto-detected from remote url if not provided)"
    )]
    pub id: Option<String>,
    #[arg(long, default_value = "origin", help = "Name of the git remote to use")]
    pub remote: String,
    #[arg(long, help = "Strip the 'generated by Shipit' line from the release notes")]
    pub no_sign: bool,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    /// Open a merge/pull request from a source branch to a target branch
    B2b(B2bArgs),
    /// Create an annotated tag on a branch with formatted release notes
    B2t(B2tArgs),
    /// Create a platform release from an existing annotated tag
    T2r(T2rArgs),
    /// Manage shipit configuration
    Config {
        #[command(subcommand)]
        subcommand: ConfigCommands,
    },
}

#[derive(Args, Debug, Default)]
pub struct ConfigGenerateArgs {
    #[arg(long, help = "GitHub personal access token")]
    pub github_token: Option<String>,
    #[arg(long, help = "GitHub domain (defaults to github.com)")]
    pub github_domain: Option<String>,
    #[arg(long, help = "GitLab personal access token")]
    pub gitlab_token: Option<String>,
    #[arg(long, help = "GitLab domain (defaults to gitlab.com)")]
    pub gitlab_domain: Option<String>,
}

#[derive(Subcommand, Debug)]
pub enum ConfigCommands {
    /// Write the default config to the platform config directory (overwrites existing config)
    Generate(ConfigGenerateArgs),
    /// Print the current config and its file path
    Show,
}
